name: Publish

on:
  push:
    branches: [ develop ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build & Test
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: build

    - name: Publish Maven (Snapshot)
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jdk8-build-test
        arguments: build publish -x test
        properties: |
          ossrhUsername=${{ secrets.OSSRH_USER }}
          ossrhPassword=${{ secrets.OSSRH_PASS }}

    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/javadoc
